server:
  port: 8080
  servlet:
      context-path: /twitterxs
  error:
    whitelabel: 
      enabled: false #true pour les jsp, false pour les ws (permet d'afficher des erreurs)

# expose all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/twitterxs?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CET
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
       ddl-auto: none
    properties: 
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
